FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY tsconfig.json ./
COPY src ./src
RUN npm run build

FROM node:20-alpine
WORKDIR /app
COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules
COPY src/infrastructure/database/migrations ./dist/infrastructure/database/migrations
EXPOSE 3000
CMD ["node", "dist/server.js"]
